files:
  /etc/collectd/collectd.conf: |
    Hostname "demo-collectd.localhost"
    
    LoadPlugin syslog
    
    <Plugin syslog>
      LogLevel info
    </Plugin>
    
    LoadPlugin cpu
    LoadPlugin memory
    LoadPlugin processes
    
    LoadPlugin write_prometheus
    
    <Plugin "write_prometheus">
        Port "9103"
    </Plugin>
    
    LoadPlugin statsd
    
    <Plugin statsd>
      Host "0.0.0.0"
      Port "8125"
    </Plugin>

command: /etc/init.d/inetutils-syslogd start ; /etc/init.d/collectd start ; bash

publish:
  - "8125:8125/udp"
